---
.title: "Introduction"
author: "Mar Guzman"
date: "2/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(sf)
library(raster)
library(leaflet)
library(ggplot2)
library(gridExtra)
```

```{r}

# Ommar, can you please...
# - download a shapefile for Ventura county and save it in the piru_data folder
# -  

```

## Loading in data and reprojecting it with sf package

```{r}

# upload coordinates 
survey_data_load <-read.csv(here("piru_data","point_coord_20241024.csv")) %>% 
  filter(data_type == "transect") %>% 
  as.tibble()

# upload ventura county shapefile
# ven_county <- st_read(here("piru_data", ".shp")) %>%
#   st_transform(crs = 4326)


# upload group data
groups <- read.csv(here("piru_data", "groups.csv")) %>% 
  dplyr::select(c(system_ind, cluster)) %>% 
  rename(survey_location = system_ind) %>% 
  mutate(
      survey_location = as.character(survey_location), 
      cluster = as.character(cluster)
      ) %>% 
  as_tibble() 

# join survey_data_load and groups
survey_data <- survey_data_load %>% 
  left_join(groups, by = "survey_location") %>%
   mutate(survey_location = case_when(survey_location == "1.1" ~ "1.10", # old ~ new
                                 survey_location == "2.1" ~ "2.10",
                                 survey_location == "2.2" ~ "2.20",
                                   TRUE ~ survey_location)) %>% 
  rename(group = cluster) 
  

survey_sf <- st_as_sf(survey_data, coords = c("long","lat"),crs = 4326)


# plots <- st_read(here("data", "sample_plots.shp")) %>% 
#   st_transform(crs = 4326)

# sb_county <- st_read(here("data", "sb_county.shp")) %>% 
#   st_transform(crs = 4326)

```

## Static map to visualize survey locations

```{r}
survey_sf <- survey_sf %>%
  mutate(group = factor(group, levels = c("1", "3", "2", "4", "5"),
                        labels = c("NNG", "ssG", "ssF", "ssFG", "EVG")))


# Static map with ggplot2, color by "group"
static1 <- ggplot() +
  # geom_sf(data = ventura_county, fill = "lightgray", color = "black") +   # County shapefile
  geom_sf(data = (survey_sf %>%  
                    filter(str_starts(survey_location, "1"))
                  ), aes(color = group), size = 3) +           # Survey locations, colored by group
  scale_color_manual(values = c("NNG" = "yellow", 
                                "ssG" = "orange", 
                                "ssF" = "blue", 
                                "ssFG" = "purple", 
                                "EVG" = "darkgreen")) + # Customize colors for groups
  theme_bw() +
  labs(title = "Northern Site: transect locations", x = "Longitude", y = "Latitude") #+
  # expand_limits(x = c(-118.7700, -118.7550)) +  # Make sure the x-axis range includes your data points
  # scale_y_continuous(breaks = seq(34.47, 34.52, 0.01)) +  # Adjust the interval for the y-axis breaks
  # scale_x_continuous(breaks = seq(-118.7700, -118.7550, 0.001)) # Adjust the interval for the x-axis breaks
  
static2 <- ggplot() +
  # geom_sf(data = ventura_county, fill = "lightgray", color = "black") +   # County shapefile
  geom_sf(data = (survey_sf %>%  filter(str_starts(survey_location, "2"))), aes(color = group), size = 3) +           # Survey locations, colored by group
  scale_color_manual(values = c("NNG" = "yellow", 
                                "ssG" = "orange", 
                                "ssF" = "blue", 
                                "ssFG" = "purple", 
                                "EVG" = "darkgreen")) + # Customize colors for groups
  theme_bw() +
  labs(title = "Southern Site: transect locations", x = "Longitude", y = "Latitude") # +
  # expand_limits(x = c(-118.7700, -118.7550)) +  # Make sure the x-axis range includes your data points
  # scale_y_continuous(breaks = seq(34.47, 34.52, 0.01)) +  # Adjust the interval for the y-axis breaks
  # scale_x_continuous(breaks = seq(-118.7700, -118.7550, 0.001)) # Adjust the interval for the x-axis breaks
  
static3 <- ggplot() +
  # geom_sf(data = ventura_county, fill = "lightgray", color = "black") +   # County shapefile
  geom_sf(data = (survey_sf %>%  filter(str_starts(survey_location, "INT"))), aes(color = group), size = 3) +           # Survey locations, colored by group
  scale_color_manual(values = c("NNG" = "yellow", 
                                "ssG" = "orange", 
                                "ssF" = "blue", 
                                "ssFG" = "purple", 
                                "EVG" = "darkgreen")) + # Customize colors for groups
  theme_bw() +
  labs(title = "Intact Site: transect locations", x = "Longitude", y = "Latitude") # +
  # expand_limits(x = c(-118.7700, -118.7550)) +  # Make sure the x-axis range includes your data points
  # scale_y_continuous(breaks = seq(34.47, 34.52, 0.01)) +  # Adjust the interval for the y-axis breaks
  # scale_x_continuous(breaks = seq(-118.7700, -118.7550, 0.001)) # Adjust the interval for the x-axis breaks



static1
static2
static3

grid.arrange(static1, static2, static3, ncol = 1)
```

## Interactive map to visualize survey locations

```{r}

# Create a color palette function based on "group"
pal <- colorFactor(palette = c("yellow", "orange", "blue", "purple", "green"), domain = survey_sf$group)

survey_sf_buffer <- st_buffer(survey_sf, dist = 10)


# Create the interactive map
interact_1 <- leaflet() %>%
  
  #### adding terrain maps to the background
  # addProviderTiles(providers$Esri.WorldTopoMap) %>% 
   addProviderTiles(providers$Esri.WorldImagery) %>%  # Esri Imagery: High-resolution satellite imagery
  # addProviderTiles(providers$CartoDB.Positron) %>%  # light, minimalist map style suitable for data overlay
  # addProviderTiles(providers$Stamen.Terrain) %>% # A shaded terrain map, suitable for natural landscapes
  # addProviderTiles(providers$Stamen.Toner) %>%  # A high-contrast, black-and-white style that highlights features
  #addPolygons(data = survey_sf_buffer, color = "black", weight = 1, fillColor = "lightgray") %>% # Add county boundariesv
  
  addCircleMarkers(data = (survey_sf %>% filter(str_starts(survey_location, "1"))), radius = 5, color = ~pal(group), popup = ~paste("Site:", survey_location)) %>%
  setView(lng = mean(st_coordinates(survey_sf %>%  filter(str_starts(survey_location, "1")))[,1]), lat = mean(st_coordinates(survey_sf %>%  filter(str_starts(survey_location, "1")))[,2]), zoom = 17)



interact_2 <- leaflet() %>%
   addProviderTiles(providers$Esri.WorldImagery) %>%  # Esri Imagery: High-resolution satellite imagery
  #addPolygons(data = survey_sf_buffer, color = "black", weight = 1, fillColor = "lightgray") %>% # Add county boundaries
  addCircleMarkers(data = (survey_sf %>% filter(str_starts(survey_location, "2"))), radius = 5, color = ~pal(group), popup = ~paste("Site:", survey_location)) %>%
  setView(lng = mean(st_coordinates(survey_sf %>%  filter(str_starts(survey_location, "2")))[,1]), lat = mean(st_coordinates(survey_sf %>%  filter(str_starts(survey_location, "2")))[,2]), zoom = 17)



interact_3 <- leaflet() %>%
 addProviderTiles(providers$Esri.WorldImagery) %>%  # Esri Imagery: High-resolution satellite imagery
  #addPolygons(data = survey_sf_buffer, color = "black", weight = 1, fillColor = "lightgray") %>% # Add county boundaries
  addCircleMarkers(data = (survey_sf %>% filter(str_starts(survey_location, "INT"))), radius = 5, color = ~pal(group), popup = ~paste("Site:", survey_location)) %>%
  setView(lng = mean(st_coordinates(survey_sf %>%  filter(str_starts(survey_location, "INT")))[,1]), lat = mean(st_coordinates(survey_sf %>%  filter(str_starts(survey_location, "INT")))[,2]), zoom = 17)



interact_all <- leaflet() %>%
 addProviderTiles(providers$Esri.WorldImagery) %>%  # Esri Imagery: High-resolution satellite imagery
  #addPolygons(data = survey_sf_buffer, color = "black", weight = 1, fillColor = "lightgray") %>% # Add county boundaries
  addCircleMarkers(data = survey_sf, 
                   radius = 5, 
                   color = ~pal(group), 
                   popup = ~paste("Site:", survey_location)) %>%
  setView(lng = mean(st_coordinates(survey_sf)[,1]), 
          lat = mean(st_coordinates(survey_sf)[,2]), 
          zoom = 17)



interact_1
interact_2
interact_3

interact_all
```
